name: posbank_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5

  cupertino_icons: ^1.0.5
  chip_list: ^2.3.3+8
  carousel_slider: ^4.1.1
  animate_do: ^2.1.0
  fluttertoast: ^8.0.9
  http: ^0.13.5
  dio: ^4.0.6
  badges: ^2.0.3
  provider: ^6.0.3
  flutter_usb_printer: ^0.1.0+1
  checkbox_grouped: ^1.8.1
  group_radio_button: ^1.2.0
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  


flutter:

  uses-material-design: true

  assets:
    - images/
    - images/empty_cart.png